# -*- coding: utf-8 -*-
"""Rizki Adrian Bennovry_121450073_No2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AxRy4SkJCh5zzPLOIBXHBh-vzZDmJ8u

Rizki Adrian Bennovry\
121450073\
Pemograman Web RA

2. Buatlah program pengelolaan data nilai mahasiswa

Buat list berisi minimal 5 dictionary data mahasiswa (nama, nim, nilai_uts, nilai_uas, nilai_tugas)\
Hitung nilai akhir setiap mahasiswa dengan rumus: (30% UTS + 40% UAS + 30% Tugas)\
Tentukan grade setiap mahasiswa berdasarkan nilai akhir:\

- A: nilai akhir 80 atau lebih
- B: nilai akhir 70 sampai 79
- C: nilai akhir 60 sampai 69
- D: nilai akhir 50 sampai 59
- E: nilai akhir kurang dari 50

Tampilkan data mahasiswa lengkap dengan nilai akhir dan grade dalam format tabel\
Tampilkan mahasiswa dengan nilai tertinggi dan terendah
"""

import pandas as pd

# Data mahasiswa
data_mahasiswa = [
    {"nama": "Rizki", "nim": "001", "uts": 85, "uas": 90, "tugas": 80},
    {"nama": "Adrian", "nim": "002", "uts": 75, "uas": 80, "tugas": 70},
    {"nama": "Bennovry", "nim": "003", "uts": 65, "uas": 70, "tugas": 60},
    {"nama": "Taj", "nim": "004", "uts": 55, "uas": 60, "tugas": 50},
    {"nama": "Shavira", "nim": "005", "uts": 45, "uas": 50, "tugas": 40}
]

df = pd.DataFrame(data_mahasiswa)
df['akhir'] = (df['uts']*0.3 + df['uas']*0.4 + df['tugas']*0.3).round(2)

df['grade'] = pd.cut(df['akhir'],
                    bins=[0, 50, 60, 70, 80, 100],
                    labels=['E', 'D', 'C', 'B', 'A'])

print("Data Nilai Mahasiswa:")
print(df[['nim', 'nama', 'uts', 'uas', 'tugas', 'akhir', 'grade']])
 

print("\nAnalisis:")
print(f"Nilai tertinggi: {df.loc[df['akhir'].idxmax(), 'nama']} ({df['akhir'].max():.2f})")
print(f"Nilai terendah : {df.loc[df['akhir'].idxmin(), 'nama']} ({df['akhir'].min():.2f})")