# -*- coding: utf-8 -*-
"""Rizki Adrian Bennovry_121450073_No1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Q3rgMKDJ6xykeDKGi4CqR-JczFgY0sB

Rizki Adrian Bennovry\
121450073\
Pemograman Web RA

1. Buatlah program penghitung BMI (Body Mass Index) sederhana

Buatlah variabel untuk menyimpan berat badan (kg) dan tinggi badan (m)\
Hitung BMI dengan rumus: BMI = berat / (tinggi * tinggi)\
Gunakan percabangan if-elif-else untuk menampilkan kategori BMI:\
- BMI < 18.5: Berat badan kurang
- 18.5 <= BMI < 25: Berat badan normal
- 25 <= BMI < 30: Berat badan berlebih
- BMI >= 30: Obesitas

Print hasil perhitungan dan kategori BMI
"""

berat = float(input("Masukkan berat badan (kg): "))
tinggi_cm = float(input("Masukkan tinggi badan (cm): "))

tinggi_m = tinggi_cm / 100

bmi = berat / (tinggi_m ** 2)
kategori = ""

if bmi < 18.5:
    kategori = "Berat badan kurang"
elif 18.5 <= bmi < 25:
    kategori = "Berat badan normal"
elif 25 <= bmi < 30:
    kategori = "Berat badan berlebih"
else:
    kategori = "Obesitas"

print(f"\nTinggi badan: {tinggi_cm} cm = {tinggi_m} m")
print(f"BMI Anda: {bmi:.2f}")
print(f"Kategori: {kategori}")